### PR TITLE
Fix dependencies to generics and compiler generated types

### PR DESCRIPTION
**Pull request by brandhuf**
This removes all generic instances and compiler generated types from the Architecture. Generic Arguments are stored in the dependency instead of the type. Arrays are treated the same way.
New Dependencies are added for casting, referencing metadata with typeof() and typechecking with is.
Resolves issues #6 , #16  and #27 .

### CODE REVIEW

**Comment by fgather** [comment]
@brandhuf , could you check why you downgrade some versions in the PR?

**Comment by brandhuf** [comment]
> 
> 
> @brandhuf , could you check why you downgrade some versions in the PR?

Accidentally happened while merging a branch, fixed now.

**Comment by lausen1** [comment]
Will this be merged anytime soon?

**Comment by fgather** [comment]
yes :)

**Pull request merged**
