### PR TITLE
Update .NET Core 2.2 to .NET 5

### LINKED ISSUE #76: LoadAssembliesIncludingDependencies fails for record type
Hi, I have a problem when using the `LoadAssembliesIncludingDependencies` method with the `record` types introduced in C#9.
The problem occured when migrating old classes to record types. 
Suddenly I was getting `NullReferenceException`s in my unit tests (stacktrace at the end of the issue).

I tried to narrow it down and the trigger for the exception seems to be a method inside my new `record` type:
```csharp
public ProductIdentityBase CopyWithNewName(string name)
{
    return this with { Name = name };
}
```

I wanted to keep the old method signatures for creating copies of my classes.

I created a **minimal example** in my github to reproduce the issue, feel free to check it out:
https://github.com/mw-ste/ArchUnitNetRecordTypes

**Stack trace:**
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.CreateMethodBodyDependenciesRecursive(MethodBody methodBody, ICollection`1 visitedMethodReferences, List`1 bodyTypes, List`1 castTypes, List`1 typeCheckTypes, List`1 metaDataTypes, List`1 accessedFieldMembers)+MoveNext()
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.CreateMethodBodyDependenciesRecursive(MethodBody methodBody, ICollection`1 visitedMethodReferences, List`1 bodyTypes, List`1 castTypes, List`1 typeCheckTypes, List`1 metaDataTypes, List`1 accessedFieldMembers)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.CreateMethodBodyDependencies(MethodDefinition methodDefinition, MethodMember methodMember)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.<>c.<Execute>b__4_3(ValueTuple`2 tuple)
   at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.Execute()
   at ArchUnitNET.Loader.LoadTaskRegistry.<ExecuteTasks>b__1_1(Type taskKey)
   at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ArchUnitNET.Loader.LoadTaskRegistry.ExecuteTasks(List`1 taskOrder)
   at ArchUnitNET.Loader.ArchBuilder.UpdateTypeDefinitions()
   at ArchUnitNET.Loader.ArchBuilder.Build()
   at ArchUnitNET.Loader.ArchLoader.Build()
   at ArchUnitNetRecordTypes.Should.ArchUnitNetRecordShould.WorkWithRecordTypes() in E:\ArchUnitNetRecordTypes\ArchUnitNetRecordTypes.Should\ArchUnitNetRecordShould.cs:line 13
```

### PR DESCRIPTION
**Pull request by SeMuell**
To be able to create tests for new language features an upgrade of the framework has to be done (including fix #76).
- Added proposed fix from #76 and added a small unit test to verify.

### CODE REVIEW

**Comment by fgather** [comment]
Now that the Travis problem is resolved, finally some review :) Sorry that it took so long. One small question: this would break compatibility to Core2.2, right? Should we rather build it for another Target? Similar to NET Framework?

**Comment by SeMuell** [comment]
Great to hear that the Travis build is resolved. Out of curiosity, what was the problem?
The compatibility of the module itself is not touched and therefore should still work with any application that is compatible to .NET Standard 2.0 (like .NET Framework, but also .NET 5). The only thing that has been changed where the testing libraries. 
But creating tests for different targets would be nice, what do you think?

**Review by fgathercoupa — APPROVED** [review]

**Comment by fgathercoupa** [comment]
You're completely right :) It would be nice to have tests for different platforms, but let's not make it overly complicated for now :)

The problem with traffic was, that the OSS check of them took a little longer. And we ran out of credits. Unfortunately I was not aware that those were not being replenished automatically. 

Thanks for your work, I'll release it now and hope that Travis will do its job today :) But I'm sure it will.

**Comment by SeMuell** [comment]
@fgather, thanks for the explanation. Never worked with Travis before.

Unfortunately, it seems that the windows build has failed because it couldn't restore the nuget packages. Would you have some time to look into it?

**Comment by fgather** [comment]
I've already noticed. To me it looks like an issue with some local nuget cache. Somehow quite unlikely that your changes would have introduced this.

**Comment by fgather** [comment]
Ok, it seems to have been some changes due to NET5 where the nuget repository was not configured. I fixed it just to find that now the upload does not work. I'll look into it tomorrow.

**Comment by fgather** [comment]
It worked :)

**Pull request merged**
