### PR TITLE
Add basic PlantUML support for feature request #78 (2nd attempt)

### PR DESCRIPTION
**Pull request by studix**
- ArchUnitNET.Domain.PlantUml: 
new namespace which contains the PlantUML parser code ported from ArchUnit java

- TypesShould / TypeConditionsDefinition:
contains new method  _AdhereToPlantUmlDiagram_ for PlantUML based dependency checks

ExampleArchUnitTestPuml demonstrates the feature

### CODE REVIEW

**Comment by studix** [comment]
The CompilerGeneratedTypesTests is failing on the server, locally it succeeds. I don't see any connection with my changes.

**Comment by fgathercoupa** [comment]
Nice, that looks good :) As for the tests, you are right. Locally I also have a green test. However, something interesting happened when I ran the tests in Debug/Non-Release mode (unfortunately there are subtle differences in what ArchUnit can see depending on Release/Debug compilation). In the Non-Release build suddenly the ClassResidesInMultipleNamespaces test fails. 

`
Xunit.Sdk.EqualException
Assert.Equal() Failure
                                 ↓ (pos 102)
Expected: ···ut is contained in [B, A]
Actual:   ···ut is contained in [A, B]
                                 ↑ (pos 102)
`

Can you reproduce this?

As for the CompilerGeneratedTypesTests: @brandhuf , I could not reproduce whats happening on Travis. Do you have an idea?

**Comment by studix** [comment]
> ClassResidesInMultipleNamespaces

When I migrated the ClassResidesInMultipleNamespaces test to use a MemoryStream I noticed an ordering problem when creating the puml diagram in the arrange phase of the test. I fixed the test by changing the assert. 

Now that @fgather reports that the order is different on his machine I changed back to use a FileStream instead of a MemoryStream.

**Comment by brandhuf** [comment]
I ran the ClassResidesInMultipleNamespaces test multiple times and sometimes it fails and sometimes it passes. That's probably why it passed in Travis, while failing on @fgather 's machine.

As for the CompilerGeneratedTypesTests: The error seems to be related to https://docs.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystementry?view=net-5.0 so maybe it only fails on Linux while passing on Windows? I will try to replicate it.

**Comment by brandhuf** [comment]
CompilerGeneratedTypesTests fails on my linux machine aswell, I will look into it

**Comment by brandhuf** [comment]
The error in CompilerGeneratedTypesTests occurs, because FileSystemEntry contains an unsafe fixed char array, which gets compiled into a field with compiler generated field type. The test did not fail in earlier builds, because no type with an unsafe fixed array was referenced in the test assembly. #87 should fix the problem.

**Comment by fgather** [comment]
Thanks, @brandhuf for quickly fixing this. Of course now that I want to re-test everything, the Travis VM cannot find its dependencies anymore, because Microsoft seems to have decided to rearrange package structures.

**Comment by fgather** [comment]
the travis env was fixed :) I'll merge and release this. Afterwards we can clean up the equals/gethashcode functions, if we really want to.

**Comment by SeMuell** [comment]
@studix thank you very much for the effort, I highly appreciate it! 

@brandhuf it seems that the failing test is still is existent and reproducible on macOS when running debug tests (not in Release). Interesting is, that in Visual Studio Code the test is running in Release by default so I didn't found it out before.

That's the message that I got:
```console
[xUnit.net 00:00:12.65]     ArchUnitNETTests.Domain.PlantUml.ClassDiagramAssociationTest.ClassResidesInMultipleNamespaces [FAIL]
  Fehler ArchUnitNETTests.Domain.PlantUml.ClassDiagramAssociationTest.ClassResidesInMultipleNamespaces [15 ms]
  Fehlermeldung:
   Assert.Equal() Failure
                                 ↓ (pos 102)
Expected: ···ut is contained in [A, B]
Actual:   ···ut is contained in [B, A]
                                 ↑ (pos 102)
  Stapelverfolgung:
     at ArchUnitNETTests.Domain.PlantUml.ClassDiagramAssociationTest.ClassResidesInMultipleNamespaces() in /***/ArchUnitNET/ArchUnitNETTests/Domain/PlantUml/ClassDiagramAssociationTest.cs:line 105
```

**Comment by brandhuf** [comment]
Yes, my PR only fixed the failing test in CompilerGeneratedTypesTests. I ran the ClassResidesInMultipleNamespaces test multiple times in debug mode and it sometimes failed and sometimes passed. @studix Can you look into it?

**Comment by studix** [comment]
I thought this [commit](https://github.com/TNG/ArchUnitNET/commit/4d7e9f24223664d3f1cd0a09ff2da22428039ce9#diff-7d7bc5238c8963e13b13a4efb964302f4fa70f58835e0dfd942363dcaaa9df7f) would fix it. But it seems that it's unrelated to MemoryStream/FileStream.  I will have a look at it.

**Pull request merged**
